export const LOGIN_ERROR_CODE = {
  INVALID_REQUEST: 1000, // user not found or invalid credentials
  USER_NOT_FOUND: 1001, // user not found
  INVALID_CURRENT_PASSWORD: 1002, // invalid current password
  EMAIL_CAN_BE_SENT: 1003, // email can be sent
  USER_IS_ARCHIVED: 1004, // user is archived
  USER_NOT_ACTIVE: 1005, // user not active
  TOO_MANY_REQUESTS: 1008, // too many requests
  INTERNAL_SERVER_ERROR: 1009,
};

export const ME_ERROR_CODE = {
  INVALID_REQUEST: 2000, // invalid request
  USER_NOT_FOUND: 2001, // user not found
  INVALID_USER_UPDATE_PAYLOAD: 2002, // invalid user update payload

  INTERNAL_SERVER_ERROR: 2009,
};

export const STAFF_ERROR_CODE = {
  INVALID_REQUEST: 3000, // invalid request
  USER_NOT_FOUND: 3001, // user not found
  USER_JOINED_ALREADY: 3002, // user joined already
  INVITATION_NOT_CREATED: 3003, // invitation not created
  INVALID_INVITATION_TOKEN: 3004, // invalid invitation token
  INVITATION_EXPIRED: 3005, // invitation expired
  INTERNAL_SERVER_ERROR: 3006,
};

export const CLIENT_ERROR_CODE = {
  INVALID_REQUEST: 4000,
  CLIENT_NOT_FOUND: 4001,
  CLIENT_IS_EXISTING: 4002,
};

export const SHIFT_ERROR_CODE = {
  // 000 for shift
  INVALID_REQUEST: 5000,
  SHIFT_NOT_FOUND: 5001,
  SHIFT_HAPPENED: 5002,
  // 100 for staff schedules
  STAFF_SCHEDULE_NOT_FOUND: 5010,

  // 200 for task
  TASK_NOT_FOUND: 5020,
  // 300 for shift clock
  SHIFT_NOT_STARTED: 5300,
  SHIFT_ENDED: 5301,
  STAFF_SIGNATURE_REQUIRED: 5302,
  CLIENT_SIGNATURE_REQUIRED: 5303,
  STAFF_ALREADY_CLOCKED_IN: 5304,
  STAFF_ALREADY_CLOCKED_OUT: 5305,
  STAFF_NOT_CLOCKED_IN: 5306,
  INTERNAL_SERVER_ERROR: 5040,
};

export const PRICE_BOOK_ERROR_CODE = {
  INVALID_REQUEST: 6000,
  PRICE_BOOK_NOT_FOUND: 6001,
  PRICE_BOOK_IS_EXISTING: 6002,
  CANNOT_ARCHIVE_LAST_ACTIVE: 6003,
  PRICE_BOOK_RULES_OVERLAP: 6004,
  INTERNAL_SERVER_ERROR: 6006,
};

export const FUNDING_ERROR_CODE = {
  INVALID_REQUEST: 7000,
  FUNDING_NOT_FOUND: 7001,
  FUNDING_IS_EXISTING: 7002,
  INTERNAL_SERVER_ERROR: 7006,
};

export const AUTH_ERROR_CODE = {
  UNAUTHORIZED: 9999991, // unauthorized
  UNAUTHENTICATED: 9999992, // unauthenticated
  INTERNAL_SERVER_ERROR: 9999993, // internal server error
};
